# Generated by Django 2.2.4 on 2022-02-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Hi there !'),
            preserve_default=False,
        ),
    ]
