# Generated by Django 2.2.4 on 2022-02-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_text',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
