# Generated by Django 2.2.4 on 2022-02-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firs_tname',
            new_name='first_name',
        ),
    ]
