# Generated by Django 2.2.4 on 2022-02-15 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0002_auto_20220215_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
