# Generated by Django 2.2.4 on 2022-02-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_dojo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='age',
        ),
    ]
