# Generated by Django 2.2.4 on 2022-02-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_dojo_app', '0002_remove_dojo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Hi'),
        ),
    ]
