# Generated by Django 2.2.4 on 2022-02-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20220209_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='release_date',
        ),
    ]
