# Generated by Django 2.2.4 on 2022-02-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_tname', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=45)),
                ('useremail', models.CharField(max_length=255)),
                ('userpassword', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
