# Generated by Django 2.2.4 on 2022-02-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0003_user_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_dob',
        ),
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
